version: "3.9"

name: <%= name %>

services:
  creatio:
    build: 
      dockerfile: Dockerfile
    container_name: <%= container_name %>
    hostname: <%= hostname %>
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      TZ: Europe/Moscow
    working_dir: /app
    volumes:
       - ./:/app
    ports:
      - "5000:5000"
      - "5002:5002"
    networks:
      - service_network
    restart: unless-stopped

networks:
  service_network:
    name: <%= network_name %>
    external: true
